import type { Metadata } from "next";
import { Inter, Vazirmatn } from "next/font/google";
import "../shared/styles/globals.css";
import { BASE_URL } from "../../config";
import Provider from "@/shared/components/provider";

const inter = Inter({
  subsets: ["vietnamese"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});

// const vazirmatn = Vazirmatn({
//   subsets: ["latin-ext"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   variable: "--font-vazir",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: {
    default: "Next js Boilerplate",
    template: "%s | HRG",
  },
  description: "Generated by create next app",
  openGraph: {
    title: "Next js Boilerplate",
    description: "Next js Boilerplate created by HRG",
    type: "website",
    images: [
      {
        url: `${BASE_URL}/logo.png`,
        alt: "Next js Boilerplate Logo",
      },
    ],
    siteName: "Next js Boilerplate",
  },
  twitter: {
    card: "summary_large_image",
    title: "Next js Boilerplate",
    description: "Next js Boilerplate created by HRG",
    images: [`${BASE_URL}/logo.png`],
  },
  icons: {
    icon: `${BASE_URL}/logo.png`,
    apple: `${BASE_URL}/logo.png`,
  },
  alternates: {
    canonical: `${BASE_URL}/`,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${inter.variable} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
